server:
  port: 8085
spring:
  application:
    name: ldap-query-demo
  data:
    ldap:
      repositories:
        enabled: true
  ldap:
    urls: ldap://localhost:389
    base: dc=example,dc=org
    username: cn=admin,dc=example,dc=org
    password: admin
logging:
  level:
    org:
      springframework:
        ldap: debug
