server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: SpringKotlinLDAP
  data:
    ldap:
      repositories:
        enabled: true
  ldap:
    urls: ${LDAP_URL:ldap://localhost:389}
    base: ${LDAP_BASE:dc=example,dc=org}
    username: ${LDAP_USERNAME:cn=admin,dc=example,dc=org}
    password: ${LDAP_PASSWORD:admin}
logging:
  level:
    org:
      springframework:
        ldap: debug
